encoding: utf-8
port: 3000

author_name: pekary
title: Read The Tea Leaves
baseurl: ""
email: pengky812@gmail.com
github_username: Pekary

markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge