encoding: utf-8

# site settings
author_name: pekary
title: Pekary's Blog
description: "Read The Tea Leaves"
header-img: img/home-bg.jpg
email: pengky812@gmail.com
url: "pekary.github.io"
baseurl: ""


# SNS settings
github_username: Pekary



permalink: pretty

highlighter: rouge

# markdown settings
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  
 # friends
 friends: [
    {
        title: "Pooki"
        href: "http://pooki.me"
    }
 ]